# Generated by Django 4.0.4 on 2022-05-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordpoints',
            name='state',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
